reliable-master:
  container_name: "reliable-master"
  restart: "UNLESS-STOP"
  image: reliable-master
  ports:
    - "${RELIABLE_MASTER_PORT}:${RELIABLE_MASTER_PORT}"
  links:
    - mongo:mongo
    - redis:redis
  environment:
    - DB_SERVICE=mongo
    - DB_PORT=27017
    - DB_NAME=reliable_dev
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: /reliable-master/bin/reliable-master server -p ${RELIABLE_MASTER_PORT} --verbose

mongo:
  container_name: "reliable_mongo"
  restart: always
  image: mongo
  volumes:
    - /var/mongo/data/db:/data/db
    - /etc/localtime:/etc/localtime:ro

redis:
  container_name: "reliable_redis"
  restart: always
  image: redis
  volumes:
    - /etc/localtime:/etc/localtime:ro

slave_1:
  container_name: "slave_1"
  restart: always
  image: "reliable-macaca-slave"
  links:
    - reliable-master:reliable-master
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: /reliable-macaca-slave/bin/reliable-macaca-slave server -m reliable-master:8083 --verbose

