reliable-master:
  container_name: "reliable_master_${RELIABLE_ENV_CONFIG}"
  restart: always
  build: .
  ports:
    - "${RELIABLE_ENV_PORT}:${RELIABLE_ENV_PORT}"
  links:
    - mongo:mongo
    - redis:redis
  environment:
    - DB_SERVICE=mongo
    - DB_PORT=27017
    - DB_NAME=reliable_dev
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: make serve env=${RELIABLE_ENV_CONFIG}

mongo:
  container_name: "reliable_mongo_${RELIABLE_ENV_CONFIG}"
  restart: always
  image: mongo
  volumes:
    - /var/lib/mongo
    - /etc/localtime:/etc/localtime:ro
  command: "true"

redis:
  container_name: "reliable_redis_${RELIABLE_ENV_CONFIG}"
  restart: always
  image: redis
  volumes:
    - /etc/localtime:/etc/localtime:ro
