reliable-master:
  container_name: "reliable_master"
  restart: always
  build: ./pre-install/reliable-master
  ports:
    - "${RELIABLE_ENV_PORT}:${RELIABLE_ENV_PORT}"
  links:
    - mongo:mongo
    - redis:redis
  environment:
    - DB_SERVICE=mongo
    - DB_PORT=27017
    - DB_NAME=reliable_dev
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: make serve env=prod

mongo:
  container_name: "reliable_mongo"
  restart: always
  image: mongo
  volumes:
    - /var/lib/mongo
    - /etc/localtime:/etc/localtime:ro
  command: "true"

redis:
  container_name: "reliable_redis"
  restart: always
  image: redis
  volumes:
    - /etc/localtime:/etc/localtime:ro

slave1:
  container_name: "slave1"
  restart: always
  image: "local/reliable-macaca-slave"
  links:
    - reliable_master:reliable_master
  volumes:
    - /etc/localtime:/etc/localtime:ro
